#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use WR; 
use Carp qw/cluck/;

$SIG{__WARN__} = sub {
    cluck @_;
};

# Start commands for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('WR::App');
