#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use WR; 

# Start commands for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('WR::Web::Site');
